### PR TITLE
Give count the same command-line options as list.

### PR DESCRIPTION
**Pull request by fniessink**

### CODE REVIEW

**Comment by fniessink** [comment]
I think I see what you mean, let me do an update.

**Comment by fniessink** [comment]
Hope this is better? I'm not sure why the AppVeyor build fails; looks like it's trying to upgrade pip but failing?

**Comment by okken** [comment]
Let's put this in . As is, for now.
There is an opportunity to use the [count() feature of TinyDB](http://tinydb.readthedocs.io/en/latest/api.html#tinydb.database.Table.count) with queries to (maybe) improve efficiency of the count call.
However, that adds complexity to the code, and much of the list_cards() code would have to be duplicated in the count() function.

Leaving it in as is for now will make a good case study for a discussion of premature optimization, relying on tests during refactoring and optimization, using a profiler and/or timing tests, etc.

Well, that was a really long way of saying "Thank you".

Shorter: Thanks for adding this and helping with the project!

**Comment by okken** [comment]
As for appveyor, don't worry about it right now, I think pip10 is having some growing pains.

**Pull request merged**
