### PR TITLE
Implement initial GitHub Actions for Testing

### PR DESCRIPTION
**Pull request by danyeaw**
Hi @okken from the Michigan Python Meetup.

### CODE REVIEW

**Comment by danyeaw** [comment]
Probably a little bit of explanation is needed. I live setup GitHub Actions on a fork of your repo as a demo during my talk to Michigan Python. Are you interested in moving this repo from Travis and AppVeyor to Actions? If not, I can go ahead and close the PR :wink:

**Comment by okken** [comment]
I'll take a look at it. Thanks for using it as an example. That's pretty cool. How'd the presentation go?

**Comment by danyeaw** [comment]
The presentation went really well! The blog post and slides from my talk are up on [my website](https://dan.yeaw.me).

**Comment by okken** [comment]
Great write-up. Would you consider discussing it on the Test & Code podcast?

**Pull request merged**
